### PR TITLE
Using Overpass instead of the main API

### PR DESCRIPTION
**Pull request by tyrasd**
Using Overpass API features (such as filtering by timestamp, user, tags, etc.) could make this even more powerful.

I implemented a filter which only shows the edits of the last week which sounds more like "latest changes" and is better suited for larger areas.

### CODE REVIEW

**Comment by lxbarth** [comment]
@tyrasd - just tested this, I get back empty XML documents from Overpass:

```
curl "http://overpass-api.de/api/interpreter?data=(node(49.17066363836488,10.010583400726318,49.1759523642852,10.021312236785889)(newer:%222013-04-25T16:57:25.893Z%22);way(bn);node(w);way(49.17066363836488,10.010583400726318,49.1759523642852,10.021312236785889)(newer:%222013-04-25T16:57:25.893Z%22);node(w););out%20meta;" -H "Origin: http://localhost:8000" -H "Accept-Encoding: gzip,deflate,sdch" -H "Host: overpass-api.de" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.56 Safari/537.36" -H "Accept: */*" -H "Referer: http://localhost:8000/" -H "Connection: keep-alive"
```

**Comment by simon04** [comment]
There is a OSM/XAPI compatibility layer: http://wiki.openstreetmap.org/wiki/Overpass_API/XAPI_Compatibility_Layer#Map_call

**Comment by tyrasd** [comment]
Probably because this location had no changes since last week? Try [http://tyrasd.github.io/latest-changes/#17/46.49814/11.35703](http://tyrasd.github.io/latest-changes/#17/46.49814/11.35703)! Note that the "last-week only" filter is [hard-coded](https://github.com/tyrasd/latest-changes/commit/bb88475998edf2aa5b5faf4263b6c95f5ef649fe#L0R40) into the Overpass query for now.

@simon04 ~~Yes, but the xapi-mode doesn't support "advanced" features like filtering by timestamp, or does it?~~ edit: turns out it does, but it's still only a matter of taste whether one wants to use an Overpass query or the XAPI syntax.

**Comment by lxbarth** [comment]
@simon04 - thanks, I just switched to the Overpass compatibility layer and it's indeed a bit faster than the OSM API itself.

@tyrasd - 

> Probably because this location had no changes since last week?

d'oh, should have looked closer.

> turns out it does, but it's still only a matter of taste whether one wants to use an Overpass query or the XAPI syntax.

Sticking with https://github.com/osmlab/latest-changes/commit/40630f523f9a4ba383d82d1bde056e316d6468f6 for now. There isn't an equivalent for `/api/0.6/changeset/<id>` in Overpass, is there?

**Comment by simon04** [comment]
> There isn't an equivalent for `/api/0.6/changeset/<id>` in Overpass, is there?

Overpass API provides augmented diffs (http://wiki.openstreetmap.org/wiki/Overpass_API/Augmented_Diffs), but I'm not aware of an equivalent for the changeset request.

Using https://github.com/simon04/whodidit you may query metadata for changesets, e.g., http://simon04.dev.openstreetmap.org/whodidit/scripts/changeset.php?id=15925753

**Pull request closed without merging**
